name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the project
      - name: Build
        run: npm run build

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages           # The branch to deploy to
          folder: dist               # The build output folder (Vite default is `dist`)
          clean: true                # Remove old files in gh-pages branch
          commit-message: "Deploy React + Vite to GitHub Pages"

      # 6️⃣ Set custom domain (optional)
      - name: Add CNAME for custom domain
        run: echo "nofault.in" > dist/CNAME
